apiVersion: v1  # Declares that this resource is a Service
kind: Service
metadata:
  # The name of the Service
  name: mongo-express
spec:
  # Selects pods with the label 'app: mongo-express'
  selector:
    app: mongo-express
  ports:
    # Defines the protocol used (TCP)
    - protocol: TCP
      # The port on which the service will be accessible
      port: 8081
      # The port on the container to route traffic to
      targetPort: 8081
  # Service type ClusterIP makes the service accessible only within the cluster
  type: ClusterIP