apiVersion: v1  
kind: Service
metadata:
  # The name of the Service
  name: mongo-service
spec:
  # The selector matches Pods labeled with 'app: mongo'
  selector:
    app: mongo
  ports:
    - protocol: TCP  # The protocol used, in this case, TCP
      # The port that the service exposes to the cluster
      port: 27017
      # The port that the service forwards traffic to inside the container (MongoDB's default port)
      targetPort: 27017
  # Service type is ClusterIP, meaning it is only accessible within the cluster
  type: ClusterIP