apiVersion: v1
kind: Service
metadata:
  # The name of the Service
  name: node
spec:
  # The selector matches Pods labeled with 'app: node'
  selector:
    app: node
  ports:
    - protocol: TCP  # The protocol used, in this case, TCP
      # The port that the service exposes to the cluster
      port: 5000
      # The port that the service forwards traffic to inside the container
      targetPort: 5000