apiVersion: v1
kind: Service
metadata:
  # The name of the Service
  name: proxy-service
spec:
  selector:
    # Selects pods with the 'app: proxy' label
    app: proxy
  ports:
    - name: http
      # Protocol used for this port
      protocol: TCP
      # Port exposed by the Service
      port: 80
      # Port on the container to which traffic is forwarded
      targetPort: 80
    - name: https
      # Protocol used for this port
      protocol: TCP
      # Port exposed by the Service
      port: 443
      # Port on the container to which traffic is forwarded
      targetPort: 443