apiVersion: v1
kind: Service
metadata:
  # The name of the Service
  name: react
spec:
  # Selects pods with the 'app: react' label
  selector:
    app: react
  ports:
    - protocol: TCP
      # Port on the Service to expose
      port: 3000
      # Port on the container to forward traffic to
      targetPort: 3000
